resources:
  - name: artifactory_go_exampletest
    type: GitRepo
    configuration:
      path: bindushree16/project-examples
      branches:
        include: master
      gitProvider: bindu_github
  
  - name: go_buildinfo_publish_test
    type: BuildInfo
    configuration:
      sourceArtifactory: bindu_art
      buildName: go_example_build_publish_bindu
      buildNumber: 22
      
  - name: artifactorygo_module_example_2
    type: GitRepo
    configuration:
      path: bindu/artifactory-go-example
      branches:
        include: master
      gitProvider: bindu_github    
      
  - name: go_buildinfopublish_moduletest
    type: BuildInfo
    configuration:
      sourceArtifactory: bindu_art
      buildName: go_example_module_publish_bindu
      buildNumber: 32   
      
  - name: promoted_gobuild_publishtest
    type: BuildInfo
    configuration:
      sourceArtifactory: bindu_art
      buildName: promote_go_build_info_publish
      buildNumber: 42   
      
pipelines:      
  - name: bindu_gobuild_goBuildtest
    steps:
      - name: build_gotest_loacl
        type: GoBuild
        configuration:
          sourceLocation: golang-example/hello
          repository: test-localgo-bindu
          outputLocation: /tmp/dist
          outputFile: hello_bindugobuild
          inputResources:
            - name: artifactory_go_exampletest
          integrations:
            - name: bindu_art
        execution:
          onStart:
            - go version    
            
      - name: bindu_publish_go_binarytest
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: build_gotest_loacl
          targetRepository: test-localgo-bindu
          integrations:
            - name: bindu_art    
            
      - name: publish_buildtest
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_go_binarytest
          outputResources:
            - name: go_buildinfo_publish_test      
            
      - name: publishgo_moduletest_bindu
        type: GoPublishModule
        configuration:  
          sourceLocation: /tem  # required
          version: v1.0.1           # required
          targetRepository: test-go-local
          autoPublishBuildInfo: true
          integrations:
            - name: bindu_art
          inputResources:
            - name: artifactorygo_module_example_2
          outputResources:
            - name: go_buildinfopublish_moduletest       
        execution:
          onStart:
            - go version    
             
      - name: promote_build_gobinary
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local
          integrations:
            - name: bindu_art
          inputResources:
            - name: go_buildinfo_publish_test 
          outputResources:
            - name: promoted_gobuild_publishtest
    
      - name: promote_build_gotest_module
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local
          integrations:
            - name: bindu_art
          inputResources:
            - name: go_buildinfopublish_moduletest 
          outputResources:
            - name: promoted_gobuild_publishtest
