resources:
  - name: artifactory_go_exampletest
    type: GitRepo
    configuration:
      path: ~vishnur/project-examples
      branches:
        include: master
      gitProvider: varsha_bbs

  - name: artifactory_go_module_example
    type: GitRepo
    configuration:
      path: ~vishnur/artifactory-go-example
      branches:
        include: master
      gitProvider: varsha_bbs


  - name: go_build_info_publish_moduletest
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_art
      buildName: go_example_module_publish_varsha
      buildNumber: 332
      
  - name: go_build_info_publishtest
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_art
      buildName: go_example_build_publish_varsha
      buildNumber: 32
  
  - name: promoted_go_build_info_go_publishtest
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_art
      buildName: promote_go_build_info_publish
      buildNumber: 35

pipelines:
  - name: varsha_goBuildtest
    steps:
      - name: build_gotest
        type: GoBuild
        configuration:
          #nodePool: ubuntu16
          sourceLocation: golang-example/hello
          repository: test-go-local
          outputLocation: /tmp/dist
          outputFile: hello_varsha
          inputResources:
            - name: artifactory_go_exampletest
          integrations:
            - name: varsha_art
        execution:
          onStart:
            - go version
            
      - name: publish_go_binarytest
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: build_gotest
          targetRepository: test-go-local
          integrations:
            - name: varsha_art
     
      - name: publish_buildtest
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_go_binarytest
          outputResources:
            - name: go_build_info_publishtest
        
      - name: publish_go_moduletest
        type: GoPublishModule
        execution:
          onStart:
            - go version
        configuration:  
          sourceLocation: .  # required
          version: v0.0.0           # required
          targetRepository: test-go-local
          autoPublishBuildInfo: true
          integrations:
            - name: varsha_art
          inputResources:
            - name: artifactory_go_module_example
          outputResources:
            - name: go_build_info_publish_moduletest
            
      - name: promote_build_gotest_binary
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local
          integrations:
            - name: varsha_art
          inputResources:
            - name: go_build_info_publishtest #go_build_info_publish
          outputResources:
            - name: promoted_go_build_info_go_publishtest
    
      - name: promote_build_gotest_module
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local
          integrations:
            - name: varsha_art
          inputResources:
            - name: go_build_info_publish_moduletest
          outputResources:
            - name: promoted_go_build_info_go_publishtest
