pipelines:
  - name: test_gradle_pipeline
    steps:
    
      - name: gradle_build_step
        type: GradleBuild
        configuration:
          gradleCommand: clean artifactoryPublish -b build.gradle
          sourceLocation: gradle-examples/gradle-example-minimal
          configFileLocation: .
          configFileName: gradle-art-config
          inputResources:
            - name: gradle_repo
          integrations:
            - name: varsha_art
        execution:
          onStart:
            - javac -version
            - gradle --version
            
      - name: publish_build_info_gradle
        type: PublishBuildInfo
        execution:
          onStart:
            - echo "hello"
        configuration:
          inputSteps:
            - name: gradle_build_step
          outputResources:
            - name: build_info_gradle
            
      - name: promote_build_info_gradle
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local
          copy: true
          integrations:
            - name: varsha_art
          inputResources:
            - name: build_info_gradle
          outputResources:
            - name: promoted_build_info_gradle

resources:

  - name: promoted_build_info_gradle
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_art
      buildName: promotoed-full-gradle-native
      buildNumber: 1

  - name: gradle_repo
    type: GitRepo
    configuration:
      gitProvider: varsha_bbs
      path: ~vishnur/project-examples


  - name: build_info_gradle
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_art
      buildName: full-gradle-native
      buildNumber: 1
