resources:

  - name: gradleBuild
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/project-examples
      branches:
        include: master
      
  - name: gradle_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: bindu_art
      buildName: gradle-buildinfo
      buildNumber: 22    
      
  - name: gradle_PromoteBuild
    type: BuildInfo
    configuration:
      sourceArtifactory: bindu_art
      buildName: gradle-buildinfo
      buildNumber: 32    

pipelines:
  - name: test_GradleBuild
    steps:    
      - name: gradlebuild_step
        type: GradleBuild
        configuration:
          gradleCommand: clean artifactoryPublish -b build.gradle
          sourceLocation: gradle-examples/gradle-example-minimal
          configFileLocation: .
          configFileName: gradle-art-config
          inputResources:
            - name: gradleBuild
          integrations:
            - name: bindu_art
        execution:
          onStart:
            - javac -version
            - gradle --version
      
      - name: publish_buildinfo_gradle
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: gradlebuild_step        
          outputResources:
            - name: gradle_buildinfo
            
      - name: promote_gradlebuild_info
        type: PromoteBuild
        configuration:
          targetRepository: test-localgradle-bindu
          copy: true
          integrations:
            - name: bindu_art
          inputResources:
            - name: gradle_buildinfo
          outputResources:
            - name: gradle_PromoteBuild
