resources:
  - name: my_propertyBag_one
    type: PropertyBag 
    configuration:  
      key/1: value1
      key2: ""   
      
pipelines:
  - name: PipelineSteps_automation
    steps:
      - name: api_PipelineSteps
        type: Bash
        configuration:
          inputResources:
            - name: my_propertyBag_one
        execution:
          onExecute:
            - echo "executing step..."
            - printenv
