resources:
  - name: outgoingWebhook_test
    type: OutgoingWebhook
    configuration:
      webhookName: outgoingWebhook_test
      method: POST
      
pipelines:
  - name: utilityfuction_test1
    steps:
      - name: utilityFunction
        type: Bash
        configuration:
          integrations:
            - name: bindu_github
          inputResources:
            - name: outgoingWebhook_test
            
        execution:
          onExecute: 
            - printenv
            - set_payload outgoingWebhook_test testpayload.json --file      
