resources:
  - name: repo_pipe
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/ymlRepo
      
pipelines:
  - name: utilityfuction_testpipeline
    steps:
      - name: my_utilityFunction_step
        type: Bash
        configuration:
       #   integrations:
       #     - name: bindu_github
          inputResources:
            - name: repo_pipe
            
        execution:
          onExecute: 
            - printenv
            - bump_semver v3.0.0 major
            - bump_semver v3.0.0 minor
            - bump_semver v3.0.0 patch
            - bump_semver v3.0.0 beta 
            - bump_semver v1.0.0-rc rc
            - bump_semver v1.0.0-rc.12 final
           # - bump_semver v1.0.0 badaction
            
            
            - compare_git --resource repo_pipe --commit-range HEAD~2..HEAD utilityfunction.yml
      
